version: '1'

services:
  pipeline_monitor:
    image: arifinrais/akin-pipeline:pipeline-monitor-dev
    build:
      context: .
      dockerfile: src/pipeline-monitor/Dockerfile.py3
    depends_on:
      - kafka
      - enq_redis
      - zookeeper
    restart: always
  scraper:
    image: arifinrais/akin-pipeline:scraper-dev
    build:
      context: .
      dockerfile: src/scraper/Dockerfile.py3
    depends_on:
      - minio
      - enq_redis
      - create_buckets
    restart: always
  aggregator:
    image: arifinrais/akin-pipeline:engine-dev
    build:
      context: .
      dockerfile: src/engine/docker-aggregator/Dockerfile.py3
    depends_on:
      - minio
      - job_redis
      - create_buckets
    restart: always
  preparator:
    image: arifinrais/akin-pipeline:engine-dev
    build:
      context: .
      dockerfile: src/engine/docker-preparator/Dockerfile.py3
    depends_on:
      - minio
      - job_redis
      - create_buckets
      - spark
    restart: always
  analytics:
    image: arifinrais/akin-pipeline:engine-dev
    build:
      context: .
      dockerfile: src/engine/docker-preparator/Dockerfile.py3
    depends_on:
      - minio
      - job_redis
      - create_buckets
      - mongodb
    restart: always
  jobstat_hub:
    image: arifinrais/akin-pipeline:jobstat-hub-dev
    build:
      context: .
      dockerfile: src/jobstat-hub/Dockerfile.py3
    depends_on:
      - kafka
      - job_redis
      - zookeeper
    restart: always
  data_server:
    image: arifinrais/akin-pipeline:data-server-dev
    build:
      context: .
      dockerfile: src/data-server/Dockerfile.py3
    depends_on:
      - mongodb
    restart: always
    ports:
      - "3001:3001"
  minio:
    # viewable at http://127.0.0.1:9001/
    image: minio/minio:RELEASE.2020-03-14T02-21-58Z
    container_name: minio
    restart: always
    volumes:
      - minio_data:/data
    ports:
      - "9001:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /export
  create_buckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
        echo Waiting for minio service to start...;
            while ! nc -z minio 9000;
            do
              sleep 3;
            done;
            /usr/bin/mc config host add minio http://minio:9000 minio minio123;
            /usr/bin/mc mb minio/raw;
            /usr/bin/mc mb minio/aggregated;
            /usr/bin/mc mb minio/transformed;
      "
  enq_redis:
    image: redis
    # command: redis-server --requirepass redispassword
    ports:
      - "6379:6379"
    restart: always
  job_redis:
    image: redis
    # command: redis-server --requirepass redispassword
    ports:
      - "6389:6389"
    restart: always
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    restart: always
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_MESSAGE_MAX_BYTES: 2000000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
    restart: always
  spark:
    image: docker.io/bitnami/spark:3
    environment:
      SPARK_MODE: master
      SPARK_RPC_AUTHENTICATION_ENABLED: no
      SPARK_RPC_ENCRYPTION_ENABLED: no
      SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED: no
      SPARK_SSL_ENABLED: no
    ports:
      - "8080:8080"
  spark-worker-1:
    image: docker.io/bitnami/spark:3
    environment:
      SPARK_MODE: worker
      SPARK_MASTER_URL: spark://spark:7077
      SPARK_WORKER_MEMORY: 1G
      SPARK_WORKER_CORES: 1
      SPARK_RPC_AUTHENTICATION_ENABLED: no
      SPARK_RPC_ENCRYPTION_ENABLED: no
      SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED: no
      SPARK_SSL_ENABLED: no
  spark-worker-2:
    image: docker.io/bitnami/spark:3
    environment:
      SPARK_MODE: worker
      SPARK_MASTER_URL: spark://spark:7077
      SPARK_WORKER_MEMORY: 1G
      SPARK_WORKER_CORES: 1
      SPARK_RPC_AUTHENTICATION_ENABLED: no
      SPARK_RPC_ENCRYPTION_ENABLED: no
      SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED: no
      SPARK_SSL_ENABLED: no
volumes:
  minio_data: # used for minio
