apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc
  labels:
    name: minio-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  labels:
    name: minio
  namespace: default
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      name: minio
  template:
    metadata:
      name: minio
      labels:
        name: minio
    spec:
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: minio-pvc
      containers:
      - name: minio
        volumeMounts:
        - name: data 
          mountPath: "/data"
        image: minio/minio:RELEASE.2021-07-27T02-40-15Z.fips
        ports:
          - containerPort: 9000
        env:
        - name: MINIO_ROOT_USER
          value: minio
        - name: MINIO_ROOT_PASSWORD
          value: minio123
        command: ["minio", "server", "/data"]
---

apiVersion: v1
kind: Service
metadata:
  name: minio-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    name: minio
  ports:
    - name: minio
      port: 9000
      targetPort: 9000
      protocol: TCP