apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  labels:
    name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mongo
  template:
    metadata:
      labels:
        name: mongo
    spec:
      containers:
      - name: mongo
        image: mongo:4.4.8-focal
        ports:
          - containerPort: 27017
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            value: root
          - name: MONGO_INITDB_ROOT_PASSWORD
            value: mongo123 

---

apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    name: mongo
  ports:
    - name: mongo
      port: 27017
      targetPort: 27017
      protocol: TCP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-server
  labels:
    name: data-server
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      name: data-server
  template:
    metadata:
      name: data-server
      labels:
        name: data-server
    spec:
      containers:
        - name: data-server
          image: arifinrais/akin-pipeline:data-server-k8
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: data-server-configmap

---

apiVersion: v1
kind: Service
metadata:
  name: data-server-service
  namespace: default
spec:
  type: NodePort
  selector:
    name: data-server
  ports:
    - name: data-server
      protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30010
