version: '3'

services:
  minio1:
    # viewable at http://127.0.0.1:9001/
    image: minio/minio:RELEASE.2020-03-14T02-21-58Z
    container_name: minio1
    restart: always
    volumes:
      - data1:/data
    ports:
      - "9001:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /export

  # Create a bucket for the kafka data to go in  
  createbuckets:
    image: minio/mc
    depends_on:
      - minio1
    entrypoint: >
      /bin/sh -c "
        echo Waiting for minio service to start...;
            while ! nc -z minio1 9000;
            do
              sleep 3;
            done;
            /usr/bin/mc config host add minio http://minio1:9000 minio minio123;
            /usr/bin/mc mb minio/test_bucket;
            /usr/bin/mc mb minio/raw_bucket;
            /usr/bin/mc mb minio/ingested_bucket;
            /usr/bin/mc mb minio/transformed_bucket;
      "
  '''
  downloader:
    image: test/downloader
    build:
      context: .
      dockerfile: docker/downloader/Dockerfile.py3
    depends_on:
      - minio1
      - createbuckets
    restart: always
  '''
volumes:
  data1: # used for minio
