apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  labels:
    name: minio
  namespace: default
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      name: minio
  template:
    metadata:
      name: minio
      labels:
        name: minio
    spec:
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: minio-pvc
      containers:
      - name: minio
        volumeMounts:
        - name: data 
          mountPath: "/data"
        image: minio/minio:RELEASE.2021-07-27T02-40-15Z.fips
        ports:
          - containerPort: 9000
          - containerPort: 9001
        env:
        - name: MINIO_ROOT_USER
          value: minio
        - name: MINIO_ROOT_PASSWORD
          value: minio123
        command: ["server", "/export", "--console-address", "\":9001\""]
        readinessProbe:
          httpGet:
            path: /minio/health/ready
            port: 9000
          initialDelaySeconds: 120
          periodSeconds: 20
        livenessProbe:
          httpGet:
            path: /minio/health/live
            port: 9000
          initialDelaySeconds: 120

---

apiVersion: v1
kind: Service
metadata:
  name: minio-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    name: minio
  ports:
    - name: minio
      port: 9000
      targetPort: 9000
      protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: minio-console-service
  namespace: default
spec:
  type: NodePort
  selector:
    name: minio
  ports:
    - name: minio
      protocol: TCP
      port: 9001
      targetPort: 9001
      nodePort: 30010