apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  labels:
    name: minio
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      name: minio
  template:
    metadata:
      name: minio
      labels:
        name: minio
    spec:
      containers:
        - name: minio
          image: minio/minio:RELEASE.2021-07-27T02-40-15Z.fips
          ports:
            - containerPort: 9000
              name: minio
            - containerPort: 9001
              name: minio-console
          env:
            - name: MINIO_ROOT_USER
              value: minio
            - name: MINIO_ROOT_PASSWORD
              value: minio123
          command: ["server", "/export", "--console-address", "\":9001\""]

---

apiVersion: v1
kind: Service
metadata:
  name: minio-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    name: minio
  ports:
    - name: minio
      port: 9000
      targetPort: 9000
      protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: minio-console-service
  namespace: default
spec:
  type: NodePort
  selector:
    name: minio
  ports:
    - name: minio-console
      protocol: TCP
      port: 9001
      targetPort: 9001
      nodePort: 30010